# Generated by Django 2.2.6 on 2020-08-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_individualclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridcols',
            name='headerClass',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='gridcols',
            name='hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gridcols',
            name='maxWidth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gridcols',
            name='resizable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gridcols',
            name='rowDrag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gridcols',
            name='type',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
