# Generated by Django 2.2.6 on 2020-08-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_auto_20200803_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridcols',
            name='filter',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
