# Generated by Django 2.2.6 on 2020-08-15 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0006_auto_20200815_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridcols',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
