# Generated by Django 2.2.6 on 2020-08-16 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0007_gridcols_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridcols',
            name='order_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gridcols',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='insurance.Dt_Option'),
        ),
    ]
